name: "Generate mail HTML signatures"

on:
  push:
    branches:
      - "main"

jobs:
  create-signature:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pandas

      - name: Generate HTML
        run: |
          python scripts/create_signature.py

      - name: Commit the new HTML files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add signatures
          git commit -m "Create mail signatures"
          
      - name: Push the files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
